[package]
name = "ir"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[features]
default = []
socket = ["dep:serde", "dep:serde_json"]

[dependencies]
whale-target = { path = "../target-spec" }
serde_json = { version = "1", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
