name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --workspace --locked --verbose
    - name: Run workspace tests with default features
      run: cargo test --workspace --locked --verbose
    - name: Run workspace tests with all features
      run: cargo test --workspace --all-features --locked --verbose
